apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: andreagiardini/hello_app
        livenessProbe:
          httpGet:
            path: /liveness
            port: 5000
        readinessProbe:
          httpGet:
            path: /readiness
            port: 5000
