---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-app-cfg
data:
  COLOR: yellow

---
apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret-env
type: Opaque
data:
  LOGIN_USER: YWRtaW4=
  LOGIN_PASS: cGFzc3dvcmQ=

---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: andreagiardini/hello_app
    envFrom:
    - configMapRef:
        name: hello-app-cfg
    - secretRef:
        name: myapp-secret-env
