---
apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret-file
type: Opaque
data:
  LOGIN_USER: YWRtaW4=
  LOGIN_PASS: cGFzc3dvcmQ=

---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: andreagiardini/hello_app
    envFrom:
    - secretRef:
        name: myapp-secret-file
