---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-app-cfg
data:
  COLOR: yellow

---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: andreagiardini/hello_app
    envFrom:
    - configMapRef:
        name: hello-app-cfg
